package com.mdorst.voidscavengers.view.text;

import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.graphics.g2d.Batch;
import com.badlogic.gdx.graphics.g2d.BitmapFont;
import com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator;

/**
 * Creates a drawable font with conveniently manipulable attributes
 */
public abstract class Font {
    // Generates a bitmap font based on the given attributes
    private final FreeTypeFontGenerator generator;
    // Specifies attributes about the font to be generated, such as size and color
    protected FreeTypeFontGenerator.FreeTypeFontParameter fontAttributes;
    // The bitmap font to be generated by `generator`
    private BitmapFont font;

    /**
     * Create a drawable font with default attributes from the provided TrueType Font (.ttf) file.
     *
     * @param path The TrueType Font file (.ttf) file representing the desired font
     */
    protected Font(String path) {
        // Create a bitmap font generator for the font specified by `path`
        generator = new FreeTypeFontGenerator(Gdx.files.internal(path));
        // Use the default font attributes
        fontAttributes = new FreeTypeFontGenerator.FreeTypeFontParameter();
        // Generate the bitmap font that we will actually be displaying
        font = generator.generateFont(fontAttributes);
    }

    /**
     * Set the font size. The default size is 16 pixels.
     *
     * @param size The specified font size in pixels
     */
    public void setSize(int size) {
        fontAttributes.size = size;
        // Since we've changed one of the font attributes,
        // we need to regenerate the bitmap font.
        font = generator.generateFont(fontAttributes);
    }

    /**
     * Draws the provided string to the provided batch at the provided position
     * using the current font.
     *
     * @param batch The batch to be drawn to
     * @param string The string to be drawn
     * @param x The X-coordinate to be drawn at
     * @param y The Y-coordinate to be drawn at
     */
    public void draw(Batch batch, String string, float x, float y) {
        font.draw(batch, string, x, y);
    }

    public void dispose() {
        font.dispose();
        generator.dispose();
    }
}
